# Generated by Django 6.1.2 on 2026-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Ábrelo cuando estés triste', max_length=200)),
                ('icono', models.CharField(default='✉️', help_text='Emoji o icono para el sobre', max_length=10)),
                ('contenido', models.TextField(help_text='Mensaje o carta especial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Vale por una cena', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles del cupón')),
                ('canjeado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Razon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ej: Tu sonrisa ilumina el día', max_length=300)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Razones',
            },
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='recuerdos/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
