# Generated by Django 6.1.2 on 2026-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baul', '0002_alter_carta_id_alter_cupon_id_alter_razon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='razon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recuerdo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
